/**
 * Resolved adversary-sheet types for the simulator.
 *
 * Source of truth: data/bestiary/cards/<id>.card.yaml (generated by
 * tools/consolidate-bestiary.ts). Those files carry English keys and Locale
 * strings { fr, en? }; the loader resolves display strings to a single locale
 * (fr by default) so the engine works with plain strings, mirroring the web
 * lib/bestiary.ts convention.
 *
 * IMPORTANT — prose vs mechanics: a card's onSuccess / onFailure / onFives are
 * human-readable prose authored for a GM ("Inflige 💢💢💢", "Déplacement [6]
 * puis inflige 💢💢"). These are display strings only. The simulator's
 * mechanical resolution of a card is owned elsewhere (keyed by the stable card
 * `id`), the same way ACTION_DEFS owns player-action mechanics — it is NOT
 * parsed out of this prose.
 */

import type { AdversaryDie, PowerTier } from './dice'
import type { CardTag } from '../combat/types'

export type { AdversaryDie, PowerTier } from './dice'
export type { CardTag } from '../combat/types'

// ─── Guard ──────────────────────────────────────────────────────────────────

/** Default guard type printed on the fiche (no `absorb`: adversaries never Encaisser). */
export type AdversaryGuardType = 'dodge' | 'block' | 'parry'

/** Fixed guard: a flat value a player's attack must meet or beat (no roll). */
export interface AdversaryGuard {
  type:  AdversaryGuardType
  value: number
}

// ─── Body parts ─────────────────────────────────────────────────────────────

/**
 * A regenerating resource conferred by an intact block, replenished at the
 * start of each round: ◇ Stability, 🫁 Endurance (fatigue buffer), 🍀 Evasion.
 */
export type AdversaryResource = 'stability' | 'endurance' | 'evasion'

/**
 * What an intact block confers (structured). `text` is the display prose; the
 * other fields are the machine-relevant capability. A block may confer a deck
 * card (`grantsCard`), a per-card cost override (`cardCost`), a regenerating
 * resource (`resource`/`amount`), or a passive immunity (`immunity`).
 *
 * Resource ops are not yet populated on the current fiches (the source resource
 * blocks are still prose-only); the fields exist for the upcoming resource pass.
 */
export interface AdversaryBlockGrant {
  /** Display prose of the conferred capability. */
  text:        string
  /** Id of a deck card this block confers while intact (dynamic deck). */
  grantsCard?: string
  /** Cost override for a card while this block is intact (cost in ⚫ points). */
  cardCost?:   { card: string; cost: number }
  /** Regenerating resource granted at round start. */
  resource?:   AdversaryResource
  /** Amount of `resource` granted (defaults to 1 when resource is set). */
  amount?:     number
  /** Status this block confers immunity to while intact (e.g. knockdown). */
  immunity?:   string
  /** Bonus armor 🛡️ conferred to all OTHER parts while intact (e.g. a carapace). */
  armorAll?:   number
  /**
   * Bonus de GARDE conféré tant que le bloc est intact (s'ajoute à la garde de
   * base). Détruire le bloc fait chuter la garde de la créature.
   */
  guard?:      number
  /** A passive trait this block confers (surfaced in the traits list, conditional on the block's integrity). */
  trait?:      { name: string; effect: string }
}

/**
 * One block of ▢ cases within a body part. While intact, it *grants* a
 * capability (see AdversaryBlockGrant). A |▢▢| block absorbs 2 💢 or 1 💔;
 * when full it is destroyed and its capability is lost. Blocks are destroyed
 * top → bottom, in array order.
 */
export interface AdversaryBlock {
  /** Number of ▢ cases in this block. */
  cases:  number
  /** Optional display name of the block (e.g. "Plastron", "Pattes antérieures"). */
  name?:  string
  grants: AdversaryBlockGrant
}

/**
 * Functional classification of a part, used by a combatant's targeting heuristic
 * (which part to attack). Priority order depends on combat style, e.g. melee
 * favours offensive > defensive > mobility > support.
 */
export type PartTag = 'offensive' | 'defensive' | 'mobility' | 'support'

/** A named body part with its own armor and one or more capability blocks. */
export interface AdversaryPart {
  /** Stable identification slug (head, body, tail, sickles, rearLeg…). */
  type:         string
  /** Display name (Tête, Corps, Serpes…). */
  name:         string
  description?: string
  /** Functional tag driving target selection (offensive/defensive/mobility/support). */
  tag?:         PartTag
  /** Armor 🛡️ reducing 💢 taken on this part (minimum 1 applied at resolution). */
  armor:        number
  blocks:       AdversaryBlock[]
}

// ─── Traits & cards ─────────────────────────────────────────────────────────

/**
 * A trait (♾️ passive / ⚒️ active). Effect is display prose; `id` is the stable
 * key wiring the trait into the engine (traits.ts) — absent for prose-only traits.
 */
export interface AdversaryTraitDef {
  id?:    string
  name:   string
  kind:   'passive' | 'active'
  effect: string
  /** Part that confers this trait (conditional on its block); absent for innate traits. */
  source?: string
}

/**
 * A card outcome's structured effect op. This is the SHARED grammar
 * (combat/effect-ops.ts) — the same vocabulary player action outcomes use;
 * the YAML-facing documentation lives in data/adversary_actions.yaml.
 */
export type AdversaryEffectOp = import('../combat/effect-ops').EffectOp

/** A card outcome: display prose + the structured effects it applies. */
export interface AdversaryOutcome {
  /** Resolved display prose ('' when the source used the `auto` sentinel). */
  text:   string
  effect: AdversaryEffectOp[]
}

/** The ⭐ Repérez X 5 outcome: fires when the roll shows at least `count` fives. */
export interface AdversaryFivesOutcome extends AdversaryOutcome {
  count: number
}

/**
 * A deck card. No flaw ⚠️. Outcomes carry both prose and structured effects
 * (see AdversaryOutcome). `id` is the stable library key.
 */
export interface AdversaryCardDef {
  /** Stable id (e.g. sickleStrike, charge) — the library key. */
  id:         string
  name:       string
  /** Base cost in action points ⚫ (integer); a block may override it (AdversaryBlockGrant.cardCost). */
  cost:       number
  /** Fatigue cost 💧 paid when playing the card — fully absorbable by 🫁 (§ coûts de fatigue). */
  fatigueCost?: number
  initiative: number
  /**
   * Card typing (shared CardTag vocabulary, same as player actions). Read by
   * traits (Sanguinaire → offensive) and agent heuristics — never inferred
   * from the effects. Empty for legacy cards not yet tagged.
   */
  tags:       CardTag[]
  /** True for ranged actions (à distance) — display legacy; `tags` is authoritative. */
  ranged?:    boolean
  /**
   * How far the blow carries, in cases (1 = adjacent, 2 = arme d'allonge).
   * Hard-coded per action in the kits, as Ewen specified.
   *
   * ABSENT = ungated. Deliberate, not an oversight: the rules have no range
   * table for shouts or bowshots, so a `cry` or a `bowShot` reaches whatever it
   * targets. Inventing a shouting distance is a rules decision, not this
   * loader's. Only melee is pinned down today.
   */
  reach?:     number
  onSuccess:  AdversaryOutcome
  onFailure:  AdversaryOutcome
  onFives?:   AdversaryFivesOutcome
  note?:      string
}

// ─── Full sheet ─────────────────────────────────────────────────────────────

/** A fully resolved adversary sheet (all display strings in one locale). */
export interface AdversarySheet {
  id:           string
  name:         string
  power:        PowerTier
  /** The creature's dice pool (typically four), from the fiche. */
  dice:         AdversaryDie[]
  description?: string
  guard:        AdversaryGuard
  /** Disposition mentale de départ posée par le meneur (défaut « aggressive »). */
  disposition?: import('./combatant').AdversaryDisposition
  speed:        { walk: number; run: number }
  /** Fatigue 💧 death-clock size (all cases checked → unconscious). */
  fatigue:      number
  /**
   * Base action points ⚫ per round (from the creature's kit; defaults to 2 when
   * absent). Adversaries have NO reaction points ⚡ — reaction cards, if any,
   * are free or cost fatigue/stability.
   */
  actions?:     number
  parts:        AdversaryPart[]
  /** Weapons/equipment — mechanically like parts, listed separately on the fiche. */
  weapons:      AdversaryPart[]
  traits:       AdversaryTraitDef[]
  cards:        AdversaryCardDef[]
}
