/**
 * Action and guard definitions for the Quadrature combat module.
 *
 * Design principles:
 *  - Action outcomes are DECLARATIVE where possible: a def carries `outcomes`
 *    (per-result lists of shared EffectOps, see combat/effect-ops.ts) and its
 *    `resolve()` is GENERATED by makeResolve — one interpreter for every
 *    standard action instead of one resolver each. Actions whose behaviour is
 *    genuinely singular (dynamic amounts, always-fire parts: Respiration,
 *    Stabiliser) keep a hand-written `resolve()` — the declared escape hatch.
 *  - Each GuardDef owns its roll (`rollDC`) and reaction-spend logic (`effects`).
 *    The guard roll is encapsulated here, not scattered across call sites.
 *  - All external code calls the unified `resolveAction()`.
 *    There is no separate path for attacks vs self-actions.
 *  - Encaisser costs 0 reactions: it is the passive default guard, always available.
 *  - Active guards (Esquive, Parade, Blocage) cost 1 reaction on first use per round.
 *
 * Success rule (§Résolution): checkRoll.total >= threshold  (equal = success)
 */

import type { CharacteristicName, SkillName } from '../character/types'
import type { RollParams, RollResult } from '../types'
import type {
  ActionId, GuardId, ActionCost, CardTag, MentalState,
  CombatantState, CombatEffect, ResolvedAction,
} from './types'
import type { AdversaryCombatant } from '../adversary/combatant'
import { buildPool, roll } from '../dieSystem'
import { effChar, isDefeated, mentalRollModifiers, canReact } from './combatant'
import { STATUS_DEFS } from './status'
import { loadPlayerActionDefs } from './actions-data'

// Grammaire et interpréteur déclaratifs : ré-exportés depuis effect-ops.ts
// (les issues elles-mêmes vivent dans data/player_actions.yaml).
export {
  makeResolve, type ActionOutcome, type ActionOutcomes, type OutcomeFlags,
} from './effect-ops'
import type { ActionOutcomes } from './effect-ops'

// ─── Attack target ────────────────────────────────────────────────────────────

/**
 * What an offensive action can target: a player character or an adversary.
 * Adversaries defend with a FIXED guard value (no roll, no reaction); their
 * damage lands on a declared body part (routed downstream via targetPart).
 * ActionDef.resolve implementations only ever read `target.id`.
 */
export type AttackTarget = CombatantState | AdversaryCombatant

// ─── ActionDef ────────────────────────────────────────────────────────────────

export interface ActionDef {
  id:            ActionId
  label:         string
  /**
   * Short tactical description of this action, used in AI prompts.
   * Summarises cost context, hit/miss/crit/flaw outcomes in one line.
   */
  description:   string
  initiative:    number
  cost:          ActionCost
  /** Card typing (shared CardTag vocabulary, same as adversary cards). */
  tags:          CardTag[]
  /**
   * How far the blow carries, in cases (1 = adjacent, 2 = arme d'allonge).
   *
   * ⚠️ TEMPORAIRE. A character's reach is a property of the WEAPON, not of the
   * action — the same Attaque armée is reach 1 with a dagger and reach 2 with a
   * hast. Pinning it to the action is a stopgap until the weapons chantier
   * (todo #18) gives characters equipment; it is the same shortcut that makes
   * Attaque armée roll Puissance for everyone, rapier or not.
   *
   * ABSENT = ungated (social actions: the rules give no shouting distance).
   */
  reach?:        number
  prerequisite?: { skill: SkillName; minValue: number }
  /**
   * Mental states in which this action may be used (consolidation actions gate
   * on them — e.g. Résolution needs Concentré or a fear state). An EMPTY array
   * means no mental constraint. Always present.
   */
  mentalConditions: MentalState[]
  /** True for Respiration / Stabiliser: must be the first action of the round (🟢) */
  requiresFirstAction: boolean
  rollChar:      CharacteristicName
  rollSkill:     SkillName
  /** True for self-targeted actions: roll vs fixed DC, no opponent, no guard */
  selfTargeted:  boolean
  /** DC formula for self-targeted actions (reads live state for dynamic values) */
  getDC?:        (actor: CombatantState) => number
  /**
   * Declarative outcomes when the action is standard (resolve is then
   * GENERATED by makeResolve — see actionOutcomes). Absent for the custom
   * resolvers (Respiration, Stabiliser).
   */
  outcomes?:     ActionOutcomes
  /**
   * Compute all CombatEffects and log notes for this action's outcome.
   * Called after `checkRoll.total >= dc` has been evaluated.
   * Generated from `outcomes` for standard actions; hand-written only for
   * actions whose behaviour the shared grammar cannot express.
   *
   * For offensive actions `target` is always defined.
   * For self-targeted actions `target` is undefined (actor effects only).
   */
  resolve(
    outcome: { hit: boolean; critical: boolean; flaw: boolean },
    actor:   CombatantState,
    target?: AttackTarget,
  ): { effects: CombatEffect[]; notes: string[] }
}

// ─── GuardDef ─────────────────────────────────────────────────────────────────

export interface GuardDef {
  id:          GuardId
  label:       string
  cost:        ActionCost
  rollChar:    CharacteristicName
  rollSkill:   SkillName
  /**
   * Reaction speed of this guard.
   * A guard can only be used against attacks whose initiative is strictly higher:
   *   guardDef.initiative < attackDef.initiative
   *
   * Lower = faster = usable against more attacks.
   *   absorb  0  — passive; always available (no initiative constraint)
   *   dodge   2  — quick sidestep; reacts to sharp/unarmed(3), armed(5), brutal(6)
   *   parry   4  — weapon discipline; reacts to armed(5), brutal(6) only
   *   block   5  — heavy block; only reacts to brutal-strike(6)
   */
  initiative:  number
  /**
   * Number of 🟩 advantage dice granted to the **attacker** when this guard is chosen.
   *
   * Encaisser (absorb) grants 1 advantage: the defender accepts the blow without
   * actively resisting, so the attacker rolls with a free advantage die.
   * Active guards (dodge, parry, block) grant no advantage to the attacker.
   */
  attackerAdvantage?: number
  isAvailable: (defender: CombatantState) => boolean
  /**
   * Roll this guard and return the full result.
   * The total becomes the DC for any incoming attack this round.
   */
  rollDC(snapshot: CombatantState): RollResult
  /**
   * Compute CombatEffects and notes for using this guard as a reaction.
   *
   * isFirstUse = true  → first attack on this target this round:
   *   non-absorb guards spend 1 reaction; flaw = +1💧 to defender.
   * isFirstUse = false → cached guard reused; no additional cost or effect.
   *
   * critical is optional (most guards ignore it); Block uses it to grant
   * +1 🛡️ temporary protection on a critical roll (§Blocage).
   */
  effects(
    outcome:    { flaw: boolean; critical?: boolean },
    defender:   CombatantState,
    isFirstUse: boolean,
  ): { effects: CombatEffect[]; notes: string[] }
}

// ─── ActionContext (input to resolveAction) ───────────────────────────────────

export interface ActionContext {
  /** Threshold the actor's check must meet or beat */
  dc:      number
  /** The roll that established the DC (guard roll for vs-attacks) */
  dcRoll?: RollResult
  /** Which guard was used (vs-attacks only) */
  guardId?: GuardId
  /**
   * Pre-computed guard-reaction data.
   * Pass `{ effects: [], notes: [] }` for self-actions and cached guard re-uses.
   */
  guardReaction: { effects: CombatEffect[]; notes: string[] }
  /** Target snapshot for offensive actions; undefined for self-actions */
  target?: AttackTarget
}

// ─── Guard factories ──────────────────────────────────────────────────────────

/** Build a `rollDC` function from a static char + skill pair (a guard is a DEFENSIVE roll). */
function makeGuardRoll(char: CharacteristicName, skill: SkillName) {
  return (snap: CombatantState): RollResult => {
    const { rerolls, disadvantages } = mentalRollModifiers(snap.mentalState, 'defensive')
    const params = rollParamsFrom(snap, char, skill,
      disadvantages > 0 ? { disadvantages } : {})
    return roll(buildPool(params), rerolls)
  }
}

/**
 * Build a guard `effects` function.
 *  reactionCost = 0 → Encaisser: never spends a reaction; still flaws.
 *  reactionCost = 1 → Active guard: spends 1⚡ on first use this round.
 */
function makeGuardEffects(reactionCost: number) {
  return (
    outcome:    { flaw: boolean; critical?: boolean },
    defender:   CombatantState,
    isFirstUse: boolean,
  ): { effects: CombatEffect[]; notes: string[] } => {
    const effects: CombatEffect[] = []
    const notes:   string[]       = []
    if (isFirstUse && reactionCost > 0) {
      effects.push({ targetId: defender.id, kind: 'spend-reaction' })
    }
    if (outcome.flaw) {
      effects.push({ targetId: defender.id, kind: 'add-fatigue', amount: 1 })
      notes.push('⚠️ Défaut de Garde — défenseur +1💧')
    }
    return { effects, notes }
  }
}

// ─── Roll params builder ──────────────────────────────────────────────────────

/**
 * Build RollParams from a CombatantState snapshot.
 * Uses effective characteristic values (value − wounds, min 0).
 */
/**
 * Build RollParams from a CombatantState snapshot.
 * Uses effective characteristic values (value − wounds, min 0).
 * Active statuses with rollDisadvantage (e.g. Essoufflé 😮‍💨) are accumulated
 * into the disadvantages field automatically.
 */
export function rollParamsFrom(
  state:    CombatantState,
  charName: CharacteristicName,
  skill:    SkillName,
  opts:     Pick<RollParams, 'advantages' | 'disadvantages' | 'rerolls'> = {},
): RollParams {
  const statusDisadvantages = state.status.reduce(
    (sum, id) => sum + (STATUS_DEFS[id]?.rollDisadvantage ?? 0),
    0,
  )
  return {
    characteristic: effChar(state, charName),
    skill:          state.skills[skill],
    ...opts,
    disadvantages: (opts.disadvantages ?? 0) + statusDisadvantages,
  }
}

// ─── Action definitions ───────────────────────────────────────────────────────
//
// Les définitions d'actions vivent dans data/player_actions.yaml (source
// structurée, anglais + Locale) : métadonnées, tags et issues déclaratives ;
// resolve() est généré par makeResolve, les customs (Respiration, Stabiliser)
// sont branchés via le registre action-resolvers.ts. Chargement synchrone.

export const ACTION_DEFS: Record<ActionId, ActionDef> = loadPlayerActionDefs()

// ─── Guard definitions ────────────────────────────────────────────────────────

export const GUARD_DEFS: Record<GuardId, GuardDef> = {

  // Encaisser: passive default — costs 0 reactions, always available
  // initiative 0: can always absorb any attack (no speed constraint)
  // attackerAdvantage 1: no active resistance → attacker rolls with 1🟩
  absorb: {
    id: 'absorb', label: 'Encaisser',
    initiative: 0,
    attackerAdvantage: 1,
    cost: { actions: 0, reactions: 0, endPlayerRound: false },
    rollChar: 'vigor', rollSkill: 'recovery',
    isAvailable: () => true,
    rollDC:  makeGuardRoll('vigor', 'recovery'),
    effects: makeGuardEffects(0),
  },

  // Esquive: active reaction — costs 1⚡ on first use
  // initiative 2: quick sidestep, reacts to sharp-strike(3), armed-attack(5), brutal-strike(6)
  dodge: {
    id: 'dodge', label: 'Esquive',
    initiative: 2,
    cost: { actions: 0, reactions: 1, endPlayerRound: false },
    rollChar: 'agility', rollSkill: 'mobility',
    isAvailable: (d) => !isDefeated(d),
    rollDC:  makeGuardRoll('agility', 'mobility'),
    effects: makeGuardEffects(1),
  },

  // Parade: active reaction — costs 1⚡; requires a weapon (power ≥ 1 as proxy)
  // initiative 4: weapon discipline, reacts to armed-attack(5) and brutal-strike(6)
  parry: {
    id: 'parry', label: 'Parade',
    initiative: 4,
    cost: { actions: 0, reactions: 1, endPlayerRound: false },
    rollChar: 'acuity', rollSkill: 'vigilance',
    isAvailable: (d) => d.skills.power >= 1,
    rollDC:  makeGuardRoll('acuity', 'vigilance'),
    effects: makeGuardEffects(1),
  },

  // Blocage: active reaction — costs 1⚡; requires a shield (robustness ≥ 2 as proxy)
  // initiative 5: heavy block, only reacts to brutal-strike(6)
  // ✴️ Critical: the shield absorbs the blow → defender gains +1 temporary protection 🛡️
  block: {
    id: 'block', label: 'Blocage',
    initiative: 5,
    cost: { actions: 0, reactions: 1, endPlayerRound: false },
    rollChar: 'strength', rollSkill: 'robustness',
    isAvailable: (d) => d.skills.robustness >= 2,
    rollDC: makeGuardRoll('strength', 'robustness'),
    effects(outcome, defender, isFirstUse) {
      const effects: CombatEffect[] = []
      const notes:   string[]       = []
      if (isFirstUse) {
        effects.push({ targetId: defender.id, kind: 'spend-reaction' })
      }
      if (outcome.flaw) {
        effects.push({ targetId: defender.id, kind: 'add-fatigue', amount: 1 })
        notes.push('⚠️ Défaut de Garde — défenseur +1💧')
      }
      if (outcome.critical) {
        effects.push({ targetId: defender.id, kind: 'add-temp-protection', amount: 1 })
        notes.push('✴️ Critique — bouclier absorbe le choc (+1🛡️ temporaire)')
      }
      return { effects, notes }
    },
  },
}

// ─── Unified action resolution ────────────────────────────────────────────────

/**
 * Resolve a single action check — offensive or self-targeted.
 *
 * The caller is responsible for building the ActionContext:
 *  - Offensive: call getOrRollGuard() in round.ts to get dc/dcRoll/guardReaction
 *  - Self-action: ActionDef.getDC(actorLive) for dc; guardReaction = empty
 *
 * Hit condition: checkRoll.total >= ctx.dc  (equal = success, §Résolution)
 */
export function resolveAction(
  actorSnapshot: CombatantState,
  actionId:      ActionId,
  ctx:           ActionContext,
): ResolvedAction {
  const action = ACTION_DEFS[actionId]

  // Accumulate 🟩 advantages from the target's statuses (e.g. À terre 🙏, Inconscient 😵‍💫).
  // Adversary targets have no status list (parts + 3-state mental track) → 0.
  const targetAdvantages = ctx.target && 'status' in ctx.target
    ? ctx.target.status.reduce((sum, id) => sum + (STATUS_DEFS[id]?.attackerAdvantage ?? 0), 0)
    : 0
  // Accumulate 🟩 advantages from the guard choice (Encaisser grants 1 advantage to the attacker)
  const guardAdvantage = ctx.guardId != null
    ? (GUARD_DEFS[ctx.guardId].attackerAdvantage ?? 0)
    : 0
  const totalAdvantages = targetAdvantages + guardAdvantage
  // Mental track: an attack is an OFFENSIVE roll (self-targeted actions are neither).
  const mentalMods = action.selfTargeted
    ? { rerolls: 0, disadvantages: 0 }
    : mentalRollModifiers(actorSnapshot.mentalState, 'offensive')
  const params = rollParamsFrom(actorSnapshot, action.rollChar, action.rollSkill, {
    ...(totalAdvantages > 0 ? { advantages: totalAdvantages } : {}),
    ...(mentalMods.disadvantages > 0 ? { disadvantages: mentalMods.disadvantages } : {}),
    ...(mentalMods.rerolls > 0 ? { rerolls: mentalMods.rerolls } : {}),
  })
  const checkRoll = roll(buildPool(params), params.rerolls ?? 0)

  const hit      = checkRoll.total >= ctx.dc
  const critical = checkRoll.critical
  const flaw     = checkRoll.flaw

  const { effects: actionEffects, notes: actionNotes } =
    action.resolve({ hit, critical, flaw }, actorSnapshot, ctx.target)

  // Log the guard-based advantage so it appears in the action trace
  const guardAdvantageNotes: string[] = guardAdvantage > 0
    ? [`🟩 Avantage — Encaisser (défense passive)`]
    : []

  return {
    actorId:   actorSnapshot.id,
    action:    actionId,
    targetId:  ctx.target?.id,
    checkRoll,
    guardId:   ctx.guardId,
    guardRoll: ctx.dcRoll,
    threshold: ctx.dc,
    hit,
    critical,
    flaw,
    effects: [...ctx.guardReaction.effects, ...actionEffects],
    notes:   [...ctx.guardReaction.notes, ...guardAdvantageNotes, ...actionNotes],
  }
}

// ─── Availability checks ──────────────────────────────────────────────────────

/**
 * True if the combatant meets all prerequisites and conditions to use this action.
 * Does NOT check resource costs (see canAffordAction).
 */
export function canUseAction(state: CombatantState, actionId: ActionId): boolean {
  if (isDefeated(state)) return false
  const def = ACTION_DEFS[actionId]
  if (def.prerequisite && state.skills[def.prerequisite.skill] < def.prerequisite.minValue) return false
  if (def.mentalConditions.length > 0 && !def.mentalConditions.includes(state.mentalState)) return false
  if (def.requiresFirstAction && state.firstActionPlayed) return false
  return true
}

/**
 * True if the combatant has enough resources to pay this action's cost.
 * Does NOT check prerequisites (see canUseAction).
 */
export function canAffordAction(state: CombatantState, actionId: ActionId): boolean {
  if (state.lastActionPlayed) return false
  const cost = ACTION_DEFS[actionId].cost
  if (cost.actions   > state.actions)   return false
  if (cost.reactions > state.reactions) return false
  if (cost.endPlayerRound && state.status.some(id => STATUS_DEFS[id]?.preventsEndRound)) return false
  if ((cost.fatigue ?? 0) > 0 && state.fatigue + (cost.fatigue ?? 0) >= 20) return false
  return true
}

/** True if the defender has reactions available and the guard is usable */
export function canUseGuard(state: CombatantState, guardId: GuardId): boolean {
  const def = GUARD_DEFS[guardId]
  // Terrifié : impossible d'effectuer des réactions ⚡ → seules les gardes
  // gratuites (Encaisser, 0⚡) restent disponibles.
  if (def.cost.reactions > 0 && !canReact(state)) return false
  return state.reactions >= def.cost.reactions
      && def.isAvailable(state)
}

/** All guards currently available to this combatant */
export function availableGuards(state: CombatantState): GuardId[] {
  return (['absorb', 'dodge', 'parry', 'block'] as GuardId[]).filter(g => canUseGuard(state, g))
}
