/**
 * Action and guard definitions for the Quadrature combat module.
 *
 * Design principles:
 *  - Action outcomes are DECLARATIVE where possible: a def carries `outcomes`
 *    (per-result lists of shared EffectOps, see combat/effect-ops.ts) and its
 *    `resolve()` is GENERATED by makeResolve — one interpreter for every
 *    standard action instead of one resolver each. Actions whose behaviour is
 *    genuinely singular (dynamic amounts, always-fire parts: Respiration,
 *    Stabiliser) keep a hand-written `resolve()` — the declared escape hatch.
 *  - Each GuardDef owns its roll (`rollDC`) and reaction-spend logic (`effects`).
 *    The guard roll is encapsulated here, not scattered across call sites.
 *  - All external code calls the unified `resolveAction()`.
 *    There is no separate path for attacks vs self-actions.
 *  - Encaisser costs 0 reactions: it is the passive default guard, always available.
 *  - Active guards (Esquive, Parade, Blocage) cost 1 reaction on first use per round.
 *
 * Success rule (§Résolution): checkRoll.total >= threshold  (equal = success)
 */

import type { CharacteristicName, SkillName } from '../character/types'
import type { RollParams, RollResult } from '../types'
import type {
  ActionId, GuardId, ActionCost, CardTag, MentalState, StatusEffect,
  CombatantState, CombatEffect, ResolvedAction, ActionTrigger,
} from './types'
import type { AdversaryCombatant } from '../adversary/combatant'
import { buildPool, roll } from '../dieSystem'
import { effChar, isDefeated, mentalRollModifiers, canReact } from './combatant'
import { STATUS_DEFS } from './status'
import { loadPlayerActionDefs } from './actions-data'
import { loadGuardDefs } from './guards-data'
import { applyTraitOverlays } from './traits'
import { rollSubstitutionRank } from './perks'

// Grammaire et interpréteur déclaratifs : ré-exportés depuis effect-ops.ts
// (les issues elles-mêmes vivent dans data/player_actions.yaml).
export {
  makeResolve, type ActionOutcome, type ActionOutcomes, type OutcomeFlags,
} from './effect-ops'
import type { ActionOutcomes } from './effect-ops'

// ─── Attack target ────────────────────────────────────────────────────────────

/**
 * What an offensive action can target: a player character or an adversary.
 * Adversaries defend with a FIXED guard value (no roll, no reaction); their
 * damage lands on a declared body part (routed downstream via targetPart).
 * ActionDef.resolve implementations only ever read `target.id`.
 */
export type AttackTarget = CombatantState | AdversaryCombatant

// ─── ActionDef ────────────────────────────────────────────────────────────────

export interface ActionDef {
  id:            ActionId
  label:         string
  /**
   * Short tactical description of this action, used in AI prompts.
   * Summarises cost context, hit/miss/crit/flaw outcomes in one line.
   */
  description:   string
  initiative:    number
  cost:          ActionCost
  /** Card typing (shared CardTag vocabulary, same as adversary cards). */
  tags:          CardTag[]
  /**
   * How far the blow carries, in cases (1 = adjacent, 2 = arme d'allonge).
   *
   * ⚠️ TEMPORAIRE. A character's reach is a property of the WEAPON, not of the
   * action — the same Attaque armée is reach 1 with a dagger and reach 2 with a
   * hast. Pinning it to the action is a stopgap until the weapons chantier
   * (todo #18) gives characters equipment; it is the same shortcut that makes
   * Attaque armée roll Puissance for everyone, rapier or not.
   *
   * ABSENT = ungated (social actions: the rules give no shouting distance).
   */
  reach?:        number
  /**
   * Minimum distance the weapon needs, in cases (§ equipement). A bow can't fire
   * when engaged: minRange 1 → the target must be strictly farther than 1 case.
   * Absent / 0 = no minimum (melee connects at adjacency). Future: from the weapon.
   */
  minRange?:     number
  /**
   * Déclencheur ⚡ (§ defense_reactions.md). PRÉSENT = l'action est une RÉACTION :
   * elle ne fait jamais partie du plan de manche, elle est proposée quand
   * l'événement survient (cf. combat/triggers.ts). Absente = action normale.
   */
  trigger?:      ActionTrigger
  /**
   * Statuts qui INTERDISENT l'action (§ conditions des cartes). La Course est
   * bloquée par Essoufflé, À terre, À genoux, Entravé, Immobilisé — on ne sprinte
   * ni essoufflé ni les jambes prises.
   */
  blockedByStatus?: StatusEffect[]
  /**
   * Inertie ➡️ minimale exigée (Charge/Bousculade : 3). L'action ne peut être
   * jouée que si le combattant a assez d'élan — c'est ce qui force la Course
   * juste avant, dans la bande précédente.
   */
  requiresInertia?: number
  /**
   * Action de DÉPLACEMENT : pas de garde, pas de jet d'attaque. Elle vise une
   * case-objectif (l'ennemi) mais ne l'attaque pas. Résolue par un chemin
   * branché sur le plateau (cf. la branche mouvement de resolvePlans).
   */
  movement?:     boolean
  /**
   * 🟩 que l'action s'accorde à elle-même sur son jet (la Charge est « avec 🟩 »).
   * Distinct des 🟩 venus de la cible ou de la garde.
   */
  selfAdvantage?: number
  /**
   * Inertie ➡️ que l'action POSE en se résolvant (Posture 1, Marche 2, Course 3).
   * Lu par le résolveur de mouvement ET par le planificateur, pour que la Charge
   * de la bande suivante voie l'élan que la Course vient de donner.
   */
  grantsInertia?: number
  /** Statut que l'action s'inflige (Course → Essoufflé). Miroir de blockedByStatus. */
  grantsStatus?: StatusEffect
  /**
   * Statut que l'action lève à coup sûr (Respiration → winded). Déclaratif, pour
   * que le PLANIFICATEUR sache qu'une Respiration en Bande I rend la Course
   * jouable en Bande II — le résolveur le fait déjà dans son code.
   */
  clearsStatus?: StatusEffect
  /** Budget de déplacement, en cases : fixe, ou dérivé de la Mobilité (Course = 5 + Mobilité). */
  moveBudget?:   number | ((actor: CombatantState) => number)
  prerequisite?: { skill: SkillName; minValue: number }
  /**
   * Mental states in which this action may be used (consolidation actions gate
   * on them — e.g. Résolution needs Concentré or a fear state). An EMPTY array
   * means no mental constraint. Always present.
   */
  mentalConditions: MentalState[]
  /** True for Respiration / Stabiliser: must be the first action of the round (🟢) */
  requiresFirstAction: boolean
  rollChar:      CharacteristicName
  rollSkill:     SkillName
  /** True for self-targeted actions: roll vs fixed DC, no opponent, no guard */
  selfTargeted:  boolean
  /** DC formula for self-targeted actions (reads live state for dynamic values) */
  getDC?:        (actor: CombatantState) => number
  /**
   * Declarative outcomes when the action is standard (resolve is then
   * GENERATED by makeResolve — see actionOutcomes). Absent for the custom
   * resolvers (Respiration, Stabiliser).
   */
  outcomes?:     ActionOutcomes
  /**
   * Compute all CombatEffects and log notes for this action's outcome.
   * Called after `checkRoll.total >= dc` has been evaluated.
   * Generated from `outcomes` for standard actions; hand-written only for
   * actions whose behaviour the shared grammar cannot express.
   *
   * For offensive actions `target` is always defined.
   * For self-targeted actions `target` is undefined (actor effects only).
   */
  resolve(
    outcome: { hit: boolean; critical: boolean; flaw: boolean },
    actor:   CombatantState,
    target?: AttackTarget,
  ): { effects: CombatEffect[]; notes: string[] }
}

// ─── GuardDef ─────────────────────────────────────────────────────────────────

export interface GuardDef {
  id:          GuardId
  label:       string
  cost:        ActionCost
  rollChar:    CharacteristicName
  rollSkill:   SkillName
  /**
   * VITESSE de la Garde (§ defense_reactions.md — 🕐 Vitesse de Garde).
   * Une Garde ne répond qu'aux actions dont l'initiative est ≥ à la sienne :
   *   guardDef.initiative <= attackDef.initiative
   * À défaut, le personnage Encaisse — c'est pourquoi Encaisser est gratuite.
   *
   * Plus bas = plus rapide = répond à plus de choses.
   *   absorb 1 — tout
   *   parry  2 — initiative 2 et plus (y compris la Frappe opportuniste)
   *   dodge  3 — initiative 3 et plus · evade 3 — idem
   *   block  4 — initiative 4 et plus (jamais une Frappe vive)
   */
  initiative:  number
  /**
   * Nombre de dés 🟩 concédés à l'ATTAQUANT quand cette Garde est choisie.
   *
   * Encaisser en concède 1 sans condition : on ne résiste pas activement.
   * Les Gardes actives ne concèdent que contre un type d'action précis, dit par
   * `concessionTag` — la Parade contre les tirs, l'Esquive contre les zones.
   */
  attackerAdvantage?: number
  /** Restreint la concession aux actions portant ce tag. Absent = inconditionnelle. */
  concessionTag?: CardTag
  /** Ne peut pas être brisée (Encaisser). */
  unbreakable?: boolean
  isAvailable: (defender: CombatantState) => boolean
  /**
   * Roll this guard and return the full result.
   * The total becomes the DC for any incoming attack this round.
   */
  rollDC(snapshot: CombatantState): RollResult
  /**
   * Compute CombatEffects and notes for using this guard as a reaction.
   *
   * isFirstUse = true  → first attack on this target this round:
   *   non-absorb guards spend 1 reaction; flaw = +1💧 to defender.
   * isFirstUse = false → cached guard reused; no additional cost or effect.
   *
   * critical is optional (most guards ignore it); Block uses it to grant
   * +1 🛡️ temporary protection on a critical roll (§Blocage).
   */
  effects(
    outcome:    { flaw: boolean; critical?: boolean },
    defender:   CombatantState,
    isFirstUse: boolean,
  ): { effects: CombatEffect[]; notes: string[] }
}

// ─── ActionContext (input to resolveAction) ───────────────────────────────────

export interface ActionContext {
  /** Threshold the actor's check must meet or beat */
  dc:      number
  /** The roll that established the DC (guard roll for vs-attacks) */
  dcRoll?: RollResult
  /** Which guard was used (vs-attacks only) */
  guardId?: GuardId
  /**
   * Pre-computed guard-reaction data.
   * Pass `{ effects: [], notes: [] }` for self-actions and cached guard re-uses.
   */
  guardReaction: { effects: CombatEffect[]; notes: string[] }
  /** Target snapshot for offensive actions; undefined for self-actions */
  target?: AttackTarget
}

// ─── Guard factories ──────────────────────────────────────────────────────────

/**
 * Build a `rollDC` function from a static char + skill pair (a guard is a
 * DEFENSIVE roll). `guardId` is threaded in so the roll can apply an Escrime
 * substitution (Mur de lame / Blocage à l'épée) — the closure knows which guard
 * it is, which the encapsulated `rollDC(snapshot)` otherwise wouldn't.
 */
function makeGuardRoll(char: CharacteristicName, skill: SkillName, guardId: GuardId) {
  return (snap: CombatantState): RollResult => {
    const { rerolls, disadvantages } = mentalRollModifiers(snap.mentalState, 'defensive')
    const params = rollParamsFrom(snap, char, skill,
      disadvantages > 0 ? { disadvantages } : {})
    // Arme de prédilection : le rang d'Escrime remplace la valeur de compétence.
    const sub = rollSubstitutionRank(snap, 'guard', guardId)
    if (sub != null) params.skill = sub
    return roll(buildPool(params), rerolls)
  }
}

// ─── Roll params builder ──────────────────────────────────────────────────────

/**
 * Build RollParams from a CombatantState snapshot.
 * Uses effective characteristic values (value − wounds, min 0).
 */
/**
 * Build RollParams from a CombatantState snapshot.
 * Uses effective characteristic values (value − wounds, min 0).
 * Active statuses with rollDisadvantage (e.g. Essoufflé 😮‍💨) are accumulated
 * into the disadvantages field automatically.
 */
export function rollParamsFrom(
  state:    CombatantState,
  charName: CharacteristicName,
  skill:    SkillName,
  opts:     Pick<RollParams, 'advantages' | 'disadvantages' | 'rerolls'> = {},
): RollParams {
  const statusDisadvantages = state.status.reduce(
    (sum, id) => sum + (STATUS_DEFS[id]?.rollDisadvantage ?? 0),
    0,
  )
  return {
    characteristic: effChar(state, charName),
    skill:          state.skills[skill],
    ...opts,
    disadvantages: (opts.disadvantages ?? 0) + statusDisadvantages,
  }
}

// ─── Action definitions ───────────────────────────────────────────────────────
//
// Les définitions d'actions vivent dans data/player_actions.yaml (source
// structurée, anglais + Locale) : métadonnées, tags et issues déclaratives ;
// resolve() est généré par makeResolve, les customs (Respiration, Stabiliser)
// sont branchés via le registre action-resolvers.ts. Chargement synchrone.

export const ACTION_DEFS: Record<ActionId, ActionDef> = loadPlayerActionDefs()

/**
 * La def de `actionId` **telle que ce combattant la joue** : la def de base,
 * ajustée par ses traits (§ traits.md — Momentum change le prix de la Frappe
 * brutale, pas son effet).
 *
 * C'est LE seam à préférer à `ACTION_DEFS[id]` partout où le coût est lu ou
 * dépensé. Sans trait porté, c'est exactement la même référence d'objet —
 * aucun surcoût, aucun changement de comportement.
 *
 * ⚠️ Les modes réactifs ⚒️ ne passent PAS par ici : ils AJOUTENT une variante
 * (cf. `reactionDefs`), ils ne remplacent pas la def de base.
 */
export function defFor(state: CombatantState, actionId: ActionId): ActionDef {
  return applyTraitOverlays(state, ACTION_DEFS[actionId])
}

// ─── Guard definitions ────────────────────────────────────────────────────────

/**
 * Les cinq Gardes, CHARGÉES depuis data/guards.yaml — plus aucune règle de garde
 * n'est écrite ici. Le loader reçoit `makeGuardRoll` pour que le jet applique
 * les modificateurs défensifs de l'état mental sans créer de cycle d'import.
 */
export const GUARD_DEFS: Record<GuardId, GuardDef> = loadGuardDefs(makeGuardRoll)

/**
 * 🟩 concédés à l'attaquant par le choix de Garde.
 *
 * Encaisser concède sans condition ; les Gardes actives ne concèdent que contre
 * un type d'action donné (`concessionTag`) — la Parade contre les tirs, l'Esquive
 * contre les zones. Sans tags connus (carte d'adversaire hors ACTION_DEFS), une
 * concession conditionnelle ne s'applique pas.
 */
export function guardConcession(guardId: GuardId, tags?: readonly CardTag[]): number {
  const def = GUARD_DEFS[guardId]
  const amount = def.attackerAdvantage ?? 0
  if (amount === 0) return 0
  if (!def.concessionTag) return amount
  return tags?.includes(def.concessionTag) ? amount : 0
}

/**
 * Une Garde peut-elle répondre à une action de cette initiative ?
 * § defense_reactions.md — 🕐 Vitesse de Garde : la Garde doit être au moins
 * aussi rapide que l'action (initiative ≥ à la sienne).
 */
export function guardAnswers(guardId: GuardId, attackInitiative: number): boolean {
  return GUARD_DEFS[guardId].initiative <= attackInitiative
}

// ─── Check-roll parameters (single source, shared with the planner) ───────────

/**
 * Build the EXACT RollParams an action check would use — the one arithmetic of
 * advantages (target statuses À terre/Inconscient, guard choice Encaisser,
 * selfAdvantage de la Charge) and mental-track modifiers, factored out of
 * resolveAction so the utility planner prices the same roll it will make.
 */
export function checkRollParams(
  actorSnapshot: CombatantState,
  actionId:      ActionId,
  target?:       AttackTarget,
  guardId?:      GuardId,
): RollParams {
  const action = ACTION_DEFS[actionId]

  // Accumulate 🟩 advantages from the target's statuses (e.g. À terre 🙏, Inconscient 😵‍💫).
  // Adversary targets have no status list (parts + 4-state mental track) → 0.
  const targetAdvantages = target && 'status' in target
    ? target.status.reduce((sum, id) => sum + (STATUS_DEFS[id]?.attackerAdvantage ?? 0), 0)
    : 0
  // 🟩 concédés par le choix de Garde — inconditionnels (Encaisser) ou gâtés par
  // le type d'action (la Parade ne concède que contre un tir).
  const guardAdvantage = guardId != null ? guardConcession(guardId, action.tags) : 0
  const totalAdvantages = targetAdvantages + guardAdvantage + (action.selfAdvantage ?? 0)
  // Mental track: an attack is an OFFENSIVE roll (self-targeted actions are neither).
  const mentalMods = action.selfTargeted
    ? { rerolls: 0, disadvantages: 0 }
    : mentalRollModifiers(actorSnapshot.mentalState, 'offensive')
  const params = rollParamsFrom(actorSnapshot, action.rollChar, action.rollSkill, {
    ...(totalAdvantages > 0 ? { advantages: totalAdvantages } : {}),
    ...(mentalMods.disadvantages > 0 ? { disadvantages: mentalMods.disadvantages } : {}),
    ...(mentalMods.rerolls > 0 ? { rerolls: mentalMods.rerolls } : {}),
  })
  // Arme de prédilection (Fine Lame) : le rang d'Escrime remplace la valeur de
  // compétence. Fait ICI — la seule arithmétique du jet, partagée entre le
  // planificateur (qui price) et resolveAction (qui joue).
  const sub = rollSubstitutionRank(actorSnapshot, 'action', actionId)
  if (sub != null) params.skill = sub
  return params
}

// ─── Unified action resolution ────────────────────────────────────────────────

/**
 * Resolve a single action check — offensive or self-targeted.
 *
 * The caller is responsible for building the ActionContext:
 *  - Offensive: call getOrRollGuard() in round.ts to get dc/dcRoll/guardReaction
 *  - Self-action: ActionDef.getDC(actorLive) for dc; guardReaction = empty
 *
 * Hit condition: checkRoll.total >= ctx.dc  (equal = success, §Résolution)
 */
export function resolveAction(
  actorSnapshot: CombatantState,
  actionId:      ActionId,
  ctx:           ActionContext,
): ResolvedAction {
  const action = ACTION_DEFS[actionId]
  const params = checkRollParams(actorSnapshot, actionId, ctx.target, ctx.guardId)
  const guardAdvantage = ctx.guardId != null
    ? guardConcession(ctx.guardId, action.tags)
    : 0
  const checkRoll = roll(buildPool(params), params.rerolls ?? 0)

  const hit      = checkRoll.total >= ctx.dc
  const critical = checkRoll.critical
  const flaw     = checkRoll.flaw

  const { effects: actionEffects, notes: actionNotes } =
    action.resolve({ hit, critical, flaw }, actorSnapshot, ctx.target)

  // Log the guard-based advantage so it appears in the action trace
  const guardAdvantageNotes: string[] = guardAdvantage > 0
    ? [`🟩 Avantage — Encaisser (défense passive)`]
    : []

  return {
    actorId:   actorSnapshot.id,
    action:    actionId,
    targetId:  ctx.target?.id,
    checkRoll,
    guardId:   ctx.guardId,
    guardRoll: ctx.dcRoll,
    threshold: ctx.dc,
    hit,
    critical,
    flaw,
    effects: [...ctx.guardReaction.effects, ...actionEffects],
    notes:   [...ctx.guardReaction.notes, ...guardAdvantageNotes, ...actionNotes],
  }
}

/**
 * Résout une action de DÉPLACEMENT (Marche / Course) — sans jet ni garde.
 *
 * Émet une intention `move-toward` vers la case-objectif (le résolveur la
 * détend en chemin sur le plateau), pose l'Inertie ➡️, et s'inflige son statut
 * s'il y a lieu (Course → Essoufflé). Le budget peut être fixe (Marche 3) ou
 * dérivé de la Mobilité (Course 5 + Mobilité).
 */
export function resolveMovementAction(
  actionId: ActionId,
  actor:    CombatantState,
  goalId:   string,
  away = false,
): { effects: CombatEffect[]; notes: string[] } {
  const def    = ACTION_DEFS[actionId]
  const budget  = typeof def.moveBudget === 'function' ? def.moveBudget(actor) : (def.moveBudget ?? 0)
  const effects: CombatEffect[] = [
    { targetId: actor.id, kind: 'move-toward', goalId, budget, ...(away && { away: true }) },
  ]
  const notes:   string[]       = []
  if (def.grantsInertia != null) {
    effects.push({ targetId: actor.id, kind: 'set-inertia', value: def.grantsInertia })
  }
  if (def.grantsStatus) {
    effects.push({ targetId: actor.id, kind: 'add-status', status: def.grantsStatus })
  }
  notes.push(`▶️ ${def.label} — ${away ? 'recul' : 'approche'} jusqu'à ${budget} cases, ` +
    `Inertie ➡️ ${def.grantsInertia ?? 0}` +
    (def.grantsStatus ? `, ${def.grantsStatus === 'winded' ? 'essoufflé 😮‍💨' : def.grantsStatus}` : ''))
  return { effects, notes }
}

// ─── Availability checks ──────────────────────────────────────────────────────

/**
 * True if the combatant meets all prerequisites and conditions to use this action.
 * Does NOT check resource costs (see canAffordAction).
 */
export function canUseAction(state: CombatantState, actionId: ActionId): boolean {
  if (isDefeated(state)) return false
  const def = ACTION_DEFS[actionId]
  if (def.prerequisite && state.skills[def.prerequisite.skill] < def.prerequisite.minValue) return false
  if (def.mentalConditions.length > 0 && !def.mentalConditions.includes(state.mentalState)) return false
  if (def.requiresFirstAction && state.firstActionPlayed) return false
  // Un statut bloquant interdit l'action (Course ← Essoufflé, À terre, Entravé…).
  if (def.blockedByStatus?.some(s => state.status.includes(s))) return false
  // Élan insuffisant (Charge/Bousculade exigent Inertie ➡️ 3) : il faut avoir couru avant.
  if (def.requiresInertia != null && state.inertia < def.requiresInertia) return false
  return true
}

/**
 * True if the combatant has enough resources to pay this action's cost.
 * Does NOT check prerequisites (see canUseAction).
 */
export function canAffordAction(state: CombatantState, actionId: ActionId): boolean {
  if (state.lastActionPlayed) return false
  // Le PRIX est ce que les traits touchent (Momentum) → def effective.
  const cost = defFor(state, actionId).cost
  if (cost.actions   > state.actions)   return false
  if (cost.reactions > state.reactions) return false
  if (cost.endPlayerRound && state.status.some(id => STATUS_DEFS[id]?.preventsEndRound)) return false
  if ((cost.fatigue ?? 0) > 0 && state.fatigue + (cost.fatigue ?? 0) >= 20) return false
  return true
}

/** True if the defender has reactions available and the guard is usable */
export function canUseGuard(state: CombatantState, guardId: GuardId): boolean {
  const def = GUARD_DEFS[guardId]
  // Terrifié : impossible d'effectuer des réactions ⚡ → seules les gardes
  // gratuites (Encaisser, 0⚡) restent disponibles.
  if (def.cost.reactions > 0 && !canReact(state)) return false
  return state.reactions >= def.cost.reactions
      && def.isAvailable(state)
}

/** All guards currently available to this combatant */
export function availableGuards(state: CombatantState): GuardId[] {
  return (Object.keys(GUARD_DEFS) as GuardId[]).filter(g => canUseGuard(state, g))
}
